### ISSUE TITLE
Syntax Errors on page

### ISSUE THREAD

**Issue by gkiszczak** [xiaoxinghu/repauto#1]
Hi,

I have all prerequisites installed, and I did all the steps from set up the website part of readme. 
The server is started and I'm getting only bunch of syntax errors. 

Is it possible right now to set the directory of allure reports for my tests? In which file?

Getting started guide could be better. I can help with getting started but first I need to learn how to set up the repauto properly with proper data.

Application Trace:
`app/helpers/application_helper.rb:64: syntax error, unexpected ':', expecting =>
app/helpers/application_helper.rb:64: syntax error, unexpected ',', expecting keyword_end
app/helpers/application_helper.rb:64: syntax error, unexpected ':', expecting keyword_end
app/helpers/application_helper.rb:64: syntax error, unexpected ',', expecting keyword_end
app/helpers/application_helper.rb:65: syntax error, unexpected ':', expecting keyword_end
app/helpers/application_helper.rb:100: syntax error, unexpected ':', expecting =>
app/helpers/application_helper.rb:100: syntax error, unexpected ',', expecting keyword_end
app/helpers/application_helper.rb:101: syntax error, unexpected ':', expecting keyword_end
app/helpers/application_helper.rb:101: syntax error, unexpected ')', expecting keyword_end
app/helpers/application_helper.rb:113: syntax error, unexpected ':', expecting =>
app/helpers/application_helper.rb:113: syntax error, unexpected ')', expecting keyword_end
app/helpers/application_helper.rb:120: syntax error, unexpected keyword_end, expecting end-of-input
app/controllers/application_controller.rb:1:in `<top (required)>'
app/controllers/welcome_controller.rb:1:in `<top (required)>'`

Framework trace:
http://pastebin.com/wXWec2Rd
![repauto](https://cloud.githubusercontent.com/assets/6102748/10047928/d272f07a-6210-11e5-9634-a6d89bc52c08.png)

**Comment by rohitgargfzr** [comment]
Hi,

I am also facing same issue on setting up allure dashboard.Am i missing anything, could you please guide?

Thanks,
Rohit Gupta

**Comment by xiaoxinghu** [comment]
@c0gupr2 @gkiszczak Sorry for the late reply. I was working hard on moving to React.js, MongoDB and Gulp. It is merged back to master now, checkout the [wiki page](https://github.com/xiaoxinghu/repauto/wiki/Sync-Data) for getting started. Please let me know if you find any problems, either code or the doc.
