### ISSUE TITLE
Warning & Error messages

### ISSUE THREAD

**Issue by rohitgargfzr** [xiaoxinghu/repauto#2]
On running, nom install command i see below warning messages:
npm WARN package.json repauto@ No repository field.
npm WARN package.json Dependency 'reactify' exists in both dependencies and devDependencies, using 'reactify@^1.1.0' from dependencies

Gulp build shows error message:
Task 'build' is not in your gulp file

Still see below error on running rails server

SyntaxError in WelcomeController#index

<img width="1424" alt="screen shot 2015-10-15 at 10 42 03 am" src="https://cloud.githubusercontent.com/assets/14267715/10517125/67060d84-7329-11e5-9b25-4b43d14586b2.png">

**Comment by xiaoxinghu** [comment]
@c0gupr2 The Warning does not matter, I use the package.json to manage dependency, it's not a real node package, we don't need those kind of info.
The Gulp command now default to be compile everything, so do `gulp` instead of `gulp build`. I have updated the wiki.
The error you are seeing is strange, since the helper method call is deprecated, and nothing is calling it. Try clear the browser cache.

**Comment by rohitgargfzr** [comment]
Thanks for your response. I cleaned my browser cache/downloaded new code from github and still see helper method call failing in 109 line instead of 80 now. Could you please check?

<img width="1440" alt="screen shot 2015-10-16 at 9 46 03 am" src="https://cloud.githubusercontent.com/assets/14267715/10543153/d4ab599a-73ea-11e5-8f60-a00efe8f77aa.png">

**Comment by xiaoxinghu** [comment]
@c0gupr2 This is strange, it works fine for my environment. I have done some cleanup work to cleanup some legacy code. Can you get the latest from master and try again.

**Comment by gkiszczak** [comment]
I have the same errors.

**Comment by gkiszczak** [comment]
Important things:
update your ruby to newest version,
update your rails to newest version also.
I was able to set up repauto without errors but I stuck with other problem.

**Comment by rohitgargfzr** [comment]
Thanks we are able to run latest code with new ruby/rails version.
